package id.azset.studio.data.dao;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "DBCATEGORY".
 */
@Entity
public class DBCategory {

    @Id
    private Long CategoryId;

    @NotNull
    private String Name;
    private Boolean IsDeleted;

    @Generated
    public DBCategory() {
    }

    public DBCategory(Long CategoryId) {
        this.CategoryId = CategoryId;
    }

    @Generated
    public DBCategory(Long CategoryId, String Name, Boolean IsDeleted) {
        this.CategoryId = CategoryId;
        this.Name = Name;
        this.IsDeleted = IsDeleted;
    }

    public Long getCategoryId() {
        return CategoryId;
    }

    public void setCategoryId(Long CategoryId) {
        this.CategoryId = CategoryId;
    }

    @NotNull
    public String getName() {
        return Name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(@NotNull String Name) {
        this.Name = Name;
    }

    public Boolean getIsDeleted() {
        return IsDeleted;
    }

    public void setIsDeleted(Boolean IsDeleted) {
        this.IsDeleted = IsDeleted;
    }

}
